using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace TupleAwaiterSourceGenerator.Tests;

public class TupleAwaitersTests
{
    // lang=c#
    const string SAMPLE_CODE = """
                               static async Task Method()
                               {
                                   (int n1, int n2) = await (GetValue(1), GetValue(2));
                                   (int n3, int n4) = await (GetValue(3), GetValue(4));
                               
                                   static Task<T> GetValue<T>(T number)
                                   {
                                       return Task.FromResult(number);
                                   }
                               }
                               """;

    // lang=c#
    const string EXPECTED_GENERATED_CODE = """
                                           // <auto-generated/>
                                           
                                           using System;
                                           using System.Runtime.CompilerServices;
                                           using System.Threading.Tasks;

                                           public struct Task2Awaiter<T1, T2> : INotifyCompletion
                                           {
                                               Task<T1> _task1;
                                               Task<T2> _task2;
                                               Task _whenAllTask;
                                           
                                               public Task2Awaiter(Task<T1> task1, Task<T2> task2)
                                               {
                                                   _task1 = task1;
                                                   _task2 = task2;
                                                   _whenAllTask = Task.WhenAll(task1, task2);
                                               }
                                           
                                               public bool IsCompleted => _whenAllTask.IsCompleted;
                                           
                                               public void OnCompleted(Action continuation)
                                               {
                                                   _whenAllTask.ConfigureAwait(false).GetAwaiter().OnCompleted(continuation);
                                               }
                                           
                                               public (T1, T2) GetResult()
                                               {
                                                   _whenAllTask.GetAwaiter().GetResult();
                                                   return (_task1.Result, _task2.Result);
                                               }
                                           }
                                           
                                           
                                           """;

    [Fact]
    public void GenerateTupleAwaiters()
    {
        // Arrange
        TupleAwaiterSourceGenerator generator = new();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(TupleAwaiterSourceGenerator), [CSharpSyntaxTree.ParseText(SAMPLE_CODE)]);

        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("TupleAwaiters.g.cs"));

        // Assert
        Assert.Equal(EXPECTED_GENERATED_CODE, generatedFileSyntax.GetText().ToString(), ignoreLineEndingDifferences: true);
    }
}
